module.exports = {
  SPOTIFY_CLIENT_ID: process.env.REACT_APP_SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET: process.env.REACT_APP_SPOTIFY_CLIENT_SECRET,
  SPOTIFY_REDIRECT_URI: process.env.REACT_APP_SPOTIFY_REDIRECT_URI,
};
