/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrintableCardsImport } from './routes/printable-cards'
import { Route as NewGameImport } from './routes/new-game'
import { Route as AuthImport } from './routes/auth'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PrintableCardsRoute = PrintableCardsImport.update({
  id: '/printable-cards',
  path: '/printable-cards',
  getParentRoute: () => rootRoute,
} as any)

const NewGameRoute = NewGameImport.update({
  id: '/new-game',
  path: '/new-game',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/new-game': {
      id: '/new-game'
      path: '/new-game'
      fullPath: '/new-game'
      preLoaderRoute: typeof NewGameImport
      parentRoute: typeof rootRoute
    }
    '/printable-cards': {
      id: '/printable-cards'
      path: '/printable-cards'
      fullPath: '/printable-cards'
      preLoaderRoute: typeof PrintableCardsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/new-game': typeof NewGameRoute
  '/printable-cards': typeof PrintableCardsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/new-game': typeof NewGameRoute
  '/printable-cards': typeof PrintableCardsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/new-game': typeof NewGameRoute
  '/printable-cards': typeof PrintableCardsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/auth' | '/new-game' | '/printable-cards'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/auth' | '/new-game' | '/printable-cards'
  id: '__root__' | '/' | '/about' | '/auth' | '/new-game' | '/printable-cards'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  NewGameRoute: typeof NewGameRoute
  PrintableCardsRoute: typeof PrintableCardsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  NewGameRoute: NewGameRoute,
  PrintableCardsRoute: PrintableCardsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/auth",
        "/new-game",
        "/printable-cards"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/new-game": {
      "filePath": "new-game.tsx"
    },
    "/printable-cards": {
      "filePath": "printable-cards.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
